language: ruby
sudo: false
cache: bundler
script: bundle exec rake spec
bundler_args: --without development
services:
  - redis-server
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.8
  - 2.7.4
  - jruby
  - jruby-head
  - rbx-2
jdk:
  - openjdk8
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
